# Generated by Django 5.1 on 2024-11-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
